application: pwdmail
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:

- url: /admin/.*
  script: admin/main.py
  login: admin

- url: /batch/mailmonth
  script: batch/mailmonth.py
  login: admin
